### ISSUE TITLE
Demo to Storybook

### ISSUE THREAD

**Issue by prasanna1211** [Codebrahma/React-Chat#11]
Move the demo page to story book page with multiple stories.

Similar to this https://ealush.github.io/emoji-picker-react/?selectedKind=Standalone%20picker&selectedStory=Bottom%20Navigation%20CDN%20hosted%20128px%2Fslowest&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by rishichawda** [comment]
[Added storybook to staging branch](https://github.com/Codebrahma/React-Chat/commit/06abb7f014a7f5e206810f71755fca159d5fa314)
